---
- hosts: all
  
  tasks: 
  - package:
      name: httpd
      state: present
  - copy:
      src: /root/HttpdWithHandlers/index.html
      dest: /var/www/html   
    notify: HandelIt     
    
  handlers:   
    - name: HandelIt
      service:
        name: httpd
        state: restarted   
